// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBSS5KM0URXDMFKxJtSVfVUiYxiKN3Hf64',
//     appId: '1:24578296332:web:a057a49353b441f47b3c29',
//     messagingSenderId: '24578296332',
//     projectId: 'vn-ecomics-java',
//     authDomain: 'vn-ecomics-java.firebaseapp.com',
//     databaseURL: 'https://vn-ecomics-java-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'vn-ecomics-java.appspot.com',
//     measurementId: 'G-3LMFT19TZM',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBLJdDsmf90_5GOYKXrQAE-IJxmCi7Kd1s',
//     appId: '1:24578296332:android:e5505b7af26152ae7b3c29',
//     messagingSenderId: '24578296332',
//     projectId: 'vn-ecomics-java',
//     databaseURL: 'https://vn-ecomics-java-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'vn-ecomics-java.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDkQ5KtLbu0GLWxX3Oz9gXgthNizSnOIj0',
//     appId: '1:24578296332:ios:cd746ab48644609f7b3c29',
//     messagingSenderId: '24578296332',
//     projectId: 'vn-ecomics-java',
//     databaseURL: 'https://vn-ecomics-java-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'vn-ecomics-java.appspot.com',
//     iosClientId: '24578296332-4db08lleblu4fl8e1h7hq8k37ied530i.apps.googleusercontent.com',
//     iosBundleId: 'com.example.economic',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDkQ5KtLbu0GLWxX3Oz9gXgthNizSnOIj0',
//     appId: '1:24578296332:ios:cd746ab48644609f7b3c29',
//     messagingSenderId: '24578296332',
//     projectId: 'vn-ecomics-java',
//     databaseURL: 'https://vn-ecomics-java-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'vn-ecomics-java.appspot.com',
//     iosClientId: '24578296332-4db08lleblu4fl8e1h7hq8k37ied530i.apps.googleusercontent.com',
//     iosBundleId: 'com.example.economic',
//   );
// }
